name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Show Swift Version
        run: xcrun swift --version
      
      - name: Build Application
        run: |
          ./build.sh
      
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: BTCWatcher.app.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
